version: '3'
services:
 dbMysql:
   image: mysql:8.0
   command: --default-authentication-plugin=mysql_native_password
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: crud_laravel
   ports:
     - 3306:3306
 
 phpmyadmin:
   image: phpmyadmin
   ports:
     - 8080:80
   environment:
     - PMA_ARBITRARY=1
   links:
     - dbMysql:dbMysql
